"""empty message

Revision ID: d9b7859c460c
Revises: bee585ec1768
Create Date: 2022-01-11 15:35:09.448347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b7859c460c'
down_revision = 'bee585ec1768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_book_name_key', 'books', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('books_book_name_key', 'books', ['book_name'])
    # ### end Alembic commands ###
