"""empty message

Revision ID: 7a1e31428b1c
Revises: d9b7859c460c
Create Date: 2022-01-13 10:26:47.766947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1e31428b1c'
down_revision = 'd9b7859c460c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tagged_notes', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tagged_notes', 'id')
    # ### end Alembic commands ###
